Toon_project/urls.py
from django.contrib import admin
from django.urls import path, include
from serving.views import base, result_12,result_13
from serving.views import download_combined_image
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',base, name='base'),
    path('result_12/', result_12, name='result_12'),
    path('result_13/', result_13, name='result_13'), 
    path('pybo/', include('pybo.urls')), 
    path('combined_image/', download_combined_image, name='combined_image'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
]

templates/main.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Anyticon</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
  
    <form method="post" enctype="multipart/form-data"> 
        {% csrf_token %}
        <textarea name="input_text" cols="40" rows="5"></textarea>
        <br>
        <input type="file" name="input_image">  
        <br>
        <input type="submit" value="Classify">
    </form>

{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/navbar.html
 <!DOCTYPE html>
 <html data-wf-domain="test-ab6ceb.webflow.io" data-wf-page="64687ef9231ed90e8fb5002c" data-wf-site="64687ef9231ed90e8fb50029">
 
 <head>
     <meta charset="utf-8" />
     <title>Test</title>
     <meta content="width=device-width, initial-scale=1" name="viewport" />
     <meta content="Webflow" name="generator" />
     <link href="https://uploads-ssl.webflow.com/64687ef9231ed90e8fb50029/css/test-ab6ceb.webflow.6835518e9.css"
         rel="stylesheet" type="text/css" />
     <link href="https://fonts.googleapis.com" rel="preconnect" />
     <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous" />
     <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
     <script type="text/javascript">
         WebFont.load({
             google: {
                 families: [
                     "Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"
                 ]
             }
         });
     </script>
     <script type="text/javascript">
         !function (o, c) {
             var n = c.documentElement,
                 t = " w-mod-";
             n.className += t + "js",
                 ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
         }(window, document);
     </script>
     <link href="https://uploads-ssl.webflow.com/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
     <link href="https://uploads-ssl.webflow.com/img/webclip.png" rel="apple-touch-icon" />
     <style>
         .w-row {
           flex-direction: column !important;
         }
     </style>
       
 </head>
 
 <body>
     <div class="w-row">
         <div class="w-col w-col-4" style="flex-direction: column;">
             <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                 data-easing2="ease" role="banner" class="w-nav">
                 <div class="container w-container">
                     <nav role="navigation" class="w-nav-menu">
                         <a href="{% url 'base' %}" class="nav-link w-nav-link">Home</a>
                         <a href="{% url 'pybo:index' %}" class="nav-link w-nav-link">Community</a>
                     </nav>
                     <div class="w-nav-button">
                         <div class="w-icon-nav-menu"></div>
                     </div>
                 </div>
             </div>
         </div>
         <div class="w-col w-col-4">
             <h1 class="heading">
                 <strong><em class="italic-text">AnyTicon.</em></strong>
             </h1>
         </div>
         <div class="w-col w-col-4">
             <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                 data-easing2="ease" role="banner" class="w-nav">
                 <div class="container-2 w-container">
                     <div class="w-nav-button">
                         <div class="w-icon-nav-menu"></div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <script
         src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=64687ef9231ed90e8fb50029"
         type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://uploads-ssl.webflow.com/64687ef9231ed90e8fb50029/js/webflow.4f5735fda.js"
         type="text/javascript"></script>
 </body>
 
 </html>
 
     <script
         src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=64687ef9231ed90e8fb50029"
         type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
     <script src="https://uploads-ssl.webflow.com/64687ef9231ed90e8fb50029/js/webflow.4f5735fda.js"
         type="text/javascript"></script>
 </body>
 
 </html>
 

templates/pybobase.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>Anyticon</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/result.html
{% load static %}
<!DOCTYPE html>
<!-- This site was created in Webflow. https://www.webflow.com --><!-- Last Published: Fri May 19 2023 23:53:06 GMT+0000 (Coordinated Universal Time) -->
<html data-wf-domain="yebins-five-star-site.webflow.io" data-wf-page="6461ead3f4af9a2a796dfba2"
    data-wf-site="6461ead3f4af9a2a796dfb9f">

<head>
    <meta charset="utf-8" />
    <title>Anyticon</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Webflow" name="generator" />
    <link
        href="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/css/yebins-five-star-site.webflow.f2fbe0669.css"
        rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script
        type="text/javascript">WebFont.load({ google: { families: ["Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"] } });</script>
    <script
        type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>
    <link href="https://uploads-ssl.webflow.com/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="https://uploads-ssl.webflow.com/img/webclip.png" rel="apple-touch-icon" />
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js.js' %}"></script>
    <link rel="stylesheet" href="static/css.css">
</head>


<body>
    <div class="columns w-row">
        <div class="column w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-5 w-container">
                    <nav role="navigation" class="w-nav-menu"><a href="/" aria-current="page"
                            class="nav-link-3 w-nav-link w--current">Community</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-col w-col-4">
            <h1 class="heading-2">AnyTicon</h1>
        </div>
        <div class="w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-6 w-container">
                    <nav role="navigation" class="w-nav-menu">
                        <a href="{% url 'base' %}"
                            class="nav-link-4 w-nav-link">Home</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="hero-stack wf-section">
        <div class="container">
            <div class="hero-wrapper-two">
                <h1 class="heading">Your Emoticon!</h1>

                <h3>Input Text: {{ input_text }}</h3>
                <h3 id="predicted-label"> Predicted Label: {{ predicted_label }}</h3>
                <div style="width: 500px; height: 500px;">
                    <h5>변환 전 : </h5>
                    <img src="{{ image_url_input }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                    <h5>표정 변환 : </h5>
                    <img src="{{ image_stargan_output }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                    <h5>화풍 변환 : </h5>
                    <img src="{{ image_cyclegan_output }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                </div>
        
                <br></br>
                <br></br>

                <p class="margin-bottom-24px-2"><strong class="bold-text">멋진 이모티콘이 완성되었습니다!<br />다시 시도하시려면 아래 버튼을 눌러주세요:)</strong></p>
                <a href="{% url 'base' %}" class="button-primary w-button"><strong>retry ♻️</strong></a>
                <button id="save-btn" class="button-2 w-button"><strong>Save 🗳️</strong></button>
            </div>
        </div>
    </section>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6461ead3f4af9a2a796dfb9f"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    <script src="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/js/webflow.4f5735fda.js"
        type="text/javascript"></script>
</body>

</html>

templates/result_12.html
{% load static %}
<!DOCTYPE html>
<!-- This site was created in Webflow. https://www.webflow.com --><!-- Last Published: Fri May 19 2023 23:53:06 GMT+0000 (Coordinated Universal Time) -->
<html data-wf-domain="yebins-five-star-site.webflow.io" data-wf-page="6461ead3f4af9a2a796dfba2"
    data-wf-site="6461ead3f4af9a2a796dfb9f">

<head>
    <meta charset="utf-8" />
    <title>Anyticon</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Webflow" name="generator" />
    <link
        href="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/css/yebins-five-star-site.webflow.f2fbe0669.css"
        rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script
        type="text/javascript">WebFont.load({ google: { families: ["Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"] } });</script>
    <script
        type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>
    <link href="https://uploads-ssl.webflow.com/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="https://uploads-ssl.webflow.com/img/webclip.png" rel="apple-touch-icon" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css.css' %}">
</head>
<body>
    <div class="columns w-row">
        <div class="column w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-5 w-container">
                    <nav role="navigation" class="w-nav-menu"><a href="/" aria-current="page"
                            class="nav-link-3 w-nav-link w--current">Community</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-col w-col-4">
            <h1 class="heading-2">AnyTicon</h1>
        </div>
        <div class="w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-6 w-container">
                    <nav role="navigation" class="w-nav-menu">
                        <a href="{% url 'base' %}"
                            class="nav-link-4 w-nav-link">Home</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="hero-stack wf-section">
        <div class="container">
            <div class="hero-wrapper-two">
                <h1 class="heading">Your Emoticon!</h1>
                <h3>Input Text: {{ input_text }}</h3>
                <h3 id="predicted-label"> Predicted Label: {{ predicted_label }}</h3>
                <div style="width: 400px; height: 350px;">
                    <h5>변환 전 : </h5>
                    <img src="{{ image_url_input }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                    <h5>표정 변환 : </h5>
                    <img src="{{ image_stargan_output }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                </div>
                <br><br>
                <p class="margin-bottom-24px-2"><strong class="bold-text">멋진 이모티콘이 완성되었습니다!<br>다시 시도하시려면 아래 버튼을 눌러주세요 :)</strong></p>
                <div style="display: flex; flex-direction: column; align-items: center;">
                    <a href="{% url 'base' %}" class="button-primary w-button"><strong style="font-size: 16px;">retry ♻️</strong></a>
                    <button id="save-btn" class="button-primary w-button"><strong>Save 📷</strong></button>
                </div>
            </div>
        </div>
    </section>

    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6461ead3f4af9a2a796dfb9f"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    <script src="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/js/webflow.4f5735fda.js"
        type="text/javascript"></script>
</body>

</html>

templates/result_13.html
{% load static %}
<!DOCTYPE html>
<!-- This site was created in Webflow. https://www.webflow.com --><!-- Last Published: Fri May 19 2023 23:53:06 GMT+0000 (Coordinated Universal Time) -->
<html data-wf-domain="yebins-five-star-site.webflow.io" data-wf-page="6461ead3f4af9a2a796dfba2"
    data-wf-site="6461ead3f4af9a2a796dfb9f">

<head>
    <meta charset="utf-8" />
    <title>Anyticon</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Webflow" name="generator" />
    <link
        href="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/css/yebins-five-star-site.webflow.f2fbe0669.css"
        rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com" rel="preconnect" />
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin="anonymous" />
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script
        type="text/javascript">WebFont.load({ google: { families: ["Exo:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic"] } });</script>
    <script
        type="text/javascript">!function (o, c) { var n = c.documentElement, t = " w-mod-"; n.className += t + "js", ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch") }(window, document);</script>
    <link href="https://uploads-ssl.webflow.com/img/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <link href="https://uploads-ssl.webflow.com/img/webclip.png" rel="apple-touch-icon" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css.css' %}">

</head>


<body>


    <div class="columns w-row">
        <div class="column w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-5 w-container">
                    <nav role="navigation" class="w-nav-menu"><a href="/" aria-current="page"
                            class="nav-link-3 w-nav-link w--current">Community</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-col w-col-4">
            <h1 class="heading-2">AnyTicon</h1>
        </div>
        <div class="w-col w-col-4">
            <div data-animation="default" data-collapse="medium" data-duration="400" data-easing="ease"
                data-easing2="ease" role="banner" class="w-nav">
                <div class="container-6 w-container">
                    <nav role="navigation" class="w-nav-menu">
                        <a href="{% url 'base' %}"
                            class="nav-link-4 w-nav-link">Home</a></nav>
                    <div class="w-nav-button">
                        <div class="w-icon-nav-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="hero-stack wf-section">
        <div class="container">
            <div class="hero-wrapper-two">
                <h1 class="heading">Your Emoticon!</h1>


                <h3>Input Text: {{ input_text }}</h3>
                <h3 id="predicted-label"> Predicted Label: {{ predicted_label }}</h3>
                <div style="width: 400px; height: 350px;">
                    <h5>변환 전 : </h5>
                    <img src="{{ image_url_input }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                    <h5>화풍 변환 : </h5>
                    <img src="{{ image_cyclegan_output }}" alt="이미지" style="max-width: 100%; max-height: 100%;">
                </div>

                <br></br>

                <p class="margin-bottom-24px-2"><strong class="bold-text">멋진 이모티콘이 완성되었습니다!<br>다시 시도하시려면 아래 버튼을 눌러주세요 :)</strong></p>
                <div style="display: flex; flex-direction: column; align-items: center;">
                    <a href="{% url 'base' %}" class="button-primary w-button"><strong style="font-size: 16px;">retry ♻️</strong></a>
                    <button id="save-btn" class="button-primary w-button"><strong>Save 📷</strong></button>
                </div>
            </div>
        </div>
    </section>
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6461ead3f4af9a2a796dfb9f"
        type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    <script src="https://uploads-ssl.webflow.com/6461ead3f4af9a2a796dfb9f/js/webflow.4f5735fda.js"
        type="text/javascript"></script>
</body>

</html>